/mob/living/carbon/alien/Life()
	AdjustParalyzed(-(1.025**AmountParalyzed()), FALSE)
	AdjustImmobilized(-(1.025**AmountImmobilized()), FALSE)
	AdjustKnockdown(-(1.025**AmountKnockdown()), FALSE)
	AdjustStun(-(1.025**AmountStun()), FALSE)
	adjustStaminaLoss(-(1.025**getStaminaLoss()), FALSE)
	return..()