/mob/living/carbon/alien/Life()
	var/para = AmountParalyzed()
	var/immob = AmountImmobilized()
	var/knock = AmountKnockdown()
	var/stund = AmountStun()

	if(para > 0)
		AdjustParalyzed(-(para**1.025), FALSE)
	if(immob > 0)
		AdjustImmobilized(-(immob**1.025), FALSE)
	if(knock > 0)
		AdjustKnockdown(-(knock**1.025), FALSE)
	if(stund > 0)
		AdjustStun(-(stund**1.025), FALSE)
	return..()